name: Release

on:
  push:
    branches: [ "Develop" ]


//these job is for build (remember we are creating another job for test)  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: yarn install
    - run: yarn build